//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtouch.CIS.Proxy.HisApiService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.xiaojd.com/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.xiaojd.com/", ConfigurationName="Newtouch.CIS.Proxy.HisApiService.HisApi")]
    public interface HisApi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Newtouch.CIS.Proxy.HisApiService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.toChatResponse toChat(Newtouch.CIS.Proxy.HisApiService.toChat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.toChatResponse> toChatAsync(Newtouch.CIS.Proxy.HisApiService.toChat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.deletePresNoResponse deletePresNo(Newtouch.CIS.Proxy.HisApiService.deletePresNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.deletePresNoResponse> deletePresNoAsync(Newtouch.CIS.Proxy.HisApiService.deletePresNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.getHisSmsJsonResponse getHisSmsJson(Newtouch.CIS.Proxy.HisApiService.getHisSmsJson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getHisSmsJsonResponse> getHisSmsJsonAsync(Newtouch.CIS.Proxy.HisApiService.getHisSmsJson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Newtouch.CIS.Proxy.HisApiService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.getPwjjResponse getPwjj(Newtouch.CIS.Proxy.HisApiService.getPwjj request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getPwjjResponse> getPwjjAsync(Newtouch.CIS.Proxy.HisApiService.getPwjj request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.getEngDataStatusResponse getEngDataStatus(Newtouch.CIS.Proxy.HisApiService.getEngDataStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getEngDataStatusResponse> getEngDataStatusAsync(Newtouch.CIS.Proxy.HisApiService.getEngDataStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Newtouch.CIS.Proxy.HisApiService.engineResponse engine(Newtouch.CIS.Proxy.HisApiService.engine request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.engineResponse> engineAsync(Newtouch.CIS.Proxy.HisApiService.engine request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="toChat", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class toChat
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string useerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public toChat()
        {
        }
        
        public toChat(string useerId, string userName)
        {
            this.useerId = useerId;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="toChatResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class toChatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public toChatResponse()
        {
        }
        
        public toChatResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePresNo", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class deletePresNo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xml;
        
        public deletePresNo()
        {
        }
        
        public deletePresNo(string xml)
        {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePresNoResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class deletePresNoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public deletePresNoResponse()
        {
        }
        
        public deletePresNoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHisSmsJson", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getHisSmsJson
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ypmcid;
        
        public getHisSmsJson()
        {
        }
        
        public getHisSmsJson(string ypmcid)
        {
            this.ypmcid = ypmcid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHisSmsJsonResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getHisSmsJsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getHisSmsJsonResponse()
        {
        }
        
        public getHisSmsJsonResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPwjj", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getPwjj
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xml;
        
        public getPwjj()
        {
        }
        
        public getPwjj(string xml)
        {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPwjjResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getPwjjResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getPwjjResponse()
        {
        }
        
        public getPwjjResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEngDataStatus", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getEngDataStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xml;
        
        public getEngDataStatus()
        {
        }
        
        public getEngDataStatus(string xml)
        {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEngDataStatusResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class getEngDataStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getEngDataStatusResponse()
        {
        }
        
        public getEngDataStatusResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="engine", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class engine
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getxml;
        
        public engine()
        {
        }
        
        public engine(string getxml)
        {
            this.getxml = getxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="engineResponse", WrapperNamespace="http://api.xiaojd.com/", IsWrapped=true)]
    public partial class engineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.xiaojd.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public engineResponse()
        {
        }
        
        public engineResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HisApiChannel : Newtouch.CIS.Proxy.HisApiService.HisApi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HisApiClient : System.ServiceModel.ClientBase<Newtouch.CIS.Proxy.HisApiService.HisApi>, Newtouch.CIS.Proxy.HisApiService.HisApi
    {
        
        public HisApiClient()
        {
        }
        
        public HisApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HisApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HisApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HisApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Newtouch.CIS.Proxy.HisApiService.toChatResponse toChat(Newtouch.CIS.Proxy.HisApiService.toChat request)
        {
            return base.Channel.toChat(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.toChatResponse> toChatAsync(Newtouch.CIS.Proxy.HisApiService.toChat request)
        {
            return base.Channel.toChatAsync(request);
        }
        
        public Newtouch.CIS.Proxy.HisApiService.deletePresNoResponse deletePresNo(Newtouch.CIS.Proxy.HisApiService.deletePresNo request)
        {
            return base.Channel.deletePresNo(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.deletePresNoResponse> deletePresNoAsync(Newtouch.CIS.Proxy.HisApiService.deletePresNo request)
        {
            return base.Channel.deletePresNoAsync(request);
        }
        
        public Newtouch.CIS.Proxy.HisApiService.getHisSmsJsonResponse getHisSmsJson(Newtouch.CIS.Proxy.HisApiService.getHisSmsJson request)
        {
            return base.Channel.getHisSmsJson(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getHisSmsJsonResponse> getHisSmsJsonAsync(Newtouch.CIS.Proxy.HisApiService.getHisSmsJson request)
        {
            return base.Channel.getHisSmsJsonAsync(request);
        }
        
        public Newtouch.CIS.Proxy.HisApiService.getPwjjResponse getPwjj(Newtouch.CIS.Proxy.HisApiService.getPwjj request)
        {
            return base.Channel.getPwjj(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getPwjjResponse> getPwjjAsync(Newtouch.CIS.Proxy.HisApiService.getPwjj request)
        {
            return base.Channel.getPwjjAsync(request);
        }
        
        public Newtouch.CIS.Proxy.HisApiService.getEngDataStatusResponse getEngDataStatus(Newtouch.CIS.Proxy.HisApiService.getEngDataStatus request)
        {
            return base.Channel.getEngDataStatus(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.getEngDataStatusResponse> getEngDataStatusAsync(Newtouch.CIS.Proxy.HisApiService.getEngDataStatus request)
        {
            return base.Channel.getEngDataStatusAsync(request);
        }
        
        public Newtouch.CIS.Proxy.HisApiService.engineResponse engine(Newtouch.CIS.Proxy.HisApiService.engine request)
        {
            return base.Channel.engine(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.CIS.Proxy.HisApiService.engineResponse> engineAsync(Newtouch.CIS.Proxy.HisApiService.engine request)
        {
            return base.Channel.engineAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
